### ISSUE TITLE
only reporting aditional information with tracks in the local library

### ISSUE THREAD

**Issue by cortegedusage** [AF-1/jivelite-darkflatskin#2]
## Checklist

❗️ **Please take a quick look at [**this checklist**](https://github.com/AF-1/sobras/wiki/Checklist-to-eliminate-common-causes-of-LMS-(plugin)-problems) to eliminate common causes of LMS (plugin) problems. Thank you.**
<br><br><br>

---

## DESCRIBE THE BUG

It seems that bitrate information and the status items are only shown
when the track is in the library. 
When I play a track from spotty or Qobuz it doesn't display this information.
but when the same track is in the library, it does display it.

also there is no information when playing a radio stream.

Apart from that it is awesome there is a new skin, thank you!!!

I'm running lms 8.4 and the latest firmware for the touch.
If I find the time I try and run it on a Joggler.

thanks,
Dennis

**Comment by AF-1** [comment]
For now, audio metadata is only displayed for local library tracks. I'll check if it's possible for remote streams.

**Comment by cortegedusage** [comment]
ah, ok. It would be great if it would also display that.
thank you

**Comment by AF-1** [comment]
1.0.**6** (available in a couple of hours) should support metadata (if available) for remote tracks (radio, streaming service).
If you have a previous version installed, please use the uninstaller from the settings > advanced menu) to uninstall the old version first. Otherwise you won't be able to install the new version.
